name: Documentation

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv

      - name: Create and activate virtual environment
        run: |
          uv venv
          . .venv/bin/activate

      - name: Install dependencies
        run: |
          uv pip install -r docs/requirements.txt
        
      - name: Build docs
        run: |
          cd docs
          uv run sphinx-build -b html -d _build/doctrees -W --keep-going . _build/html

      - name: Upload to Read the Docs
        env:
          RTD_TOKEN: ${{ secrets.RTD_TOKEN }}
          RTD_PROJECT: "django-pyhub-ai"  # Read the Docs 프로젝트 이름
        run: |
          # 빌드된 문서를 압축
          cd docs/_build
          tar -czf ./html.tar.gz html/
          
          # Read the Docs API를 통해 업로드
          curl -X POST \
            -H "Authorization: Token ${RTD_TOKEN}" \
            -F "content=@./html.tar.gz" \
            -F "format=html" \
            https://readthedocs.org/api/v3/projects/${RTD_PROJECT}/versions/latest/builds/
