name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/github-pages.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uv venv
          uv pip install -r docs/requirements.txt

      - name: Build documentation
        run: |
          make docs-build

      # .nojekyll 파일 생성하여 GitHub Pages의 Jekyll 처리 비활성화
      #  _static, _images 등의 폴더 서빙을 하기 위함.
      - name: Create .nojekyll file
        run: touch docs/_build/html/.nojekyll

      - name: Deploy to GitHub Pages Repository
        uses: JamesIves/github-pages-deploy-action@v4
        # https://github.com/settings/tokens 에서 발급
        # 다른 저장소에 배포하기 위해 repo 권한 필요
        with:
          folder: docs/_build/html
          repository-name: pyhub-kr/pyhub-kr.github.io
          token: ${{ secrets.DEPLOY_TOKEN }}
          branch: gh-pages
